platform :ios, '10.0'
use_frameworks!

flutter_application_path = '../flutter_swift_module'

load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

post_install do |installer|
  flutter_post_install(installer)
end


target 'flutter_swift' do
 
  # 安装Flutter模块
   install_all_flutter_pods(flutter_application_path)
   
end


